name: Web export

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Web-Export:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04

    steps:
    - name: Install RGBDS
      run: |
        git clone --depth 1 https://github.com/gbdev/rgbds
        cd rgbds
        make
        sudo make install

    - name: Build ROM
      run: |
        git clone --depth 1 https://github.com/pret/pokered
        cd pokered
        make
        cp -v pokered.gbc /tmp/target.gbc

    - name: Checkout Pokanalysis
      uses: actions/checkout@v3

    - name: Build Pokanalysis
      run: |
        cd extractor
        cargo build --release

    - name: Run analysis
      run: |
        extractor/target/release/pokanalysis /tmp/target.gbc www/out

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: www

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
